pipa_webapp/pipa/app/user/forms.py
# app/user/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextField
from wtforms.validators import DataRequired
from wtforms.widgets import TextArea

class UserArticleForm(FlaskForm):
    """
    Form for user to add or edit an article
    """
    pmid = StringField('ID', validators=[DataRequired()])
    title = StringField('Title', validators=[DataRequired()])
    abstract = TextField('Description or Abstract', validators=[DataRequired()], widget=TextArea())
    submit = SubmitField('Submit')

pipa_webapp/pipa/app/user/__init__.py
# app/user/__init__.py

from flask import Blueprint

user = Blueprint('user', __name__)

from . import views

pipa_webapp/pipa/app/user/views.py
# app/user/views.py

from flask import flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import user
from forms import UserArticleForm
from .. import db
from ..models import UserArticle

# User Views

@user.route('/userarticles', methods=['GET', 'POST'])
@login_required
def list_userarticles():
    """
    List articles entered by a user
    """
    try:
        userarticles = UserArticle.query.filter_by(user_id = current_user.id )
        db.session.commit()
    except:
        db.session.rollback()

    return render_template('user/userarticles/userarticles.html',
                           userarticles=userarticles, title="User Articles")

@user.route('/userarticles/add', methods=['GET', 'POST'])
@login_required
def add_userarticle():
    """
    Add a userarticle to the database
    """
    add_userarticle = True

    form = UserArticleForm()
    if form.validate_on_submit():
        userarticle = UserArticle(pmid=form.pmid.data,
                                title=form.title.data,
                                abstract=form.abstract.data,
                                user_id=current_user.id)
        try:
            # add userarticle to the database
            db.session.add(userarticle)
            db.session.commit()
            flash('You have successfully added a new article.')
        except:
            # in case userarticle id already exists
            flash('Error: article already exists or text is too long')

        # redirect to userarticles page
        return redirect(url_for('user.list_userarticles'))

    # load userarticle template
    return render_template('user/userarticles/userarticle.html', action="Add",
                           add_userarticle=add_userarticle, form=form,
                           title="Add UserArticle")

@user.route('/userarticles/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_userarticle(id):
    """
    Edit a userarticle
    """
    add_userarticle = False

    try:
        userarticle = UserArticle.query.get_or_404(id)
    except:
        userarticle = UserArticle.query.get_or_404(id)
    form = UserArticleForm(obj=userarticle)
    if form.validate_on_submit():
        userarticle.pmid = form.pmid.data
        userarticle.title = form.title.data
        userarticle.abstract = form.abstract.data
        userarticle.user_id = current_user.id
        db.session.commit()
        flash('You have successfully edited the article.')

        # redirect to the userarticles page
        return redirect(url_for('user.list_userarticles'))

    form.pmid.data = userarticle.pmid
    form.title.data = userarticle.title
    form.abstract.data = userarticle.abstract
    return render_template('user/userarticles/userarticle.html', action="Edit",
                           add_userarticle=add_userarticle, form=form,
                           userarticle=userarticle, title="Edit UserArticle")

@user.route('/userarticles/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_userarticle(id):
    """
    Delete a userarticle from the database
    """
    try:
        userarticle = UserArticle.query.get_or_404(id)
    except:
        userarticle = UserArticle.query.get_or_404(id)
    db.session.delete(userarticle)
    db.session.commit()
    flash('You have successfully deleted the article.')

    # redirect to the userarticles page
    return redirect(url_for('user.list_userarticles'))

    return render_template(title="Delete UserArticle")

pipa_webapp/pipa/app/templates/user/userarticles/userarticle.html
<!-- app/templates/user/userarticles/userarticle.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_userarticle %}
        Add UserArticle
    {% else %}
        Edit UserArticle
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_userarticle %}
                <h1>Add UserArticle</h1>
            {% else %}
                <h1>Edit UserArticle</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

pipa_webapp/pipa/app/templates/user/userarticles/userarticles.html
<!-- app/templates/user/userarticles/userarticles.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}User Articles{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Your Articles</h1>
        {% if userarticles %}
          <hr class="intro-divider" style="max-height: 480px;">
          <div class="center">

              <table class="table table-striped table-bordered" style="overflow-y: scroll;">
                <thead>
                  <tr>
                    <th width="15%"> ID </th>
                    <th width="40%"> Title </th>
                    <th width="15%"> Edit </th>
                    <th width="15%"> Delete </th>
                  </tr>
                </thead>
                <tbody>
                {% for userarticle in userarticles %}
                  <tr>
                    <td> {{ userarticle.pmid }} </td>
                    <td> {{ userarticle.title }} </td>
                    <td>
                      <a href="{{ url_for('user.edit_userarticle', id=userarticle.id) }}">
                        <i class="fa fa-pencil"></i> Edit
                      </a>
                    </td>
                    <td>
                      <a href="{{ url_for('user.delete_userarticle', id=userarticle.id) }}">
                        <i class="fa fa-trash"></i> Delete
                      </a>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>

          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No userarticles have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('user.add_userarticle') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Articles
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}